#!/bin/bash

# settings
IMG=sdcard.raw
LODEV=/dev/loop0
DMDEV=
SIZE=1024

# run as root
if [ "x$UID" != "x0" ]; then
	echo Error: root privileges required!
	exit 1
fi

# clean up

# delete image if exists
if [ -e "$IMG" ]; then
	rm -fv $"IMG"
fi

# detach loop device if necessary
losetup -d $LODEV 2>/dev/null || true

# allocate space
dd if=/dev/zero of=$IMG bs=1M count=$SIZE

# create loop device for image
LODEV=/dev/loop0
losetup $LODEV $IMG

# create partition table
fdisk $LODEV << EOF
o
n
p
1


w
q
EOF

# create device-mapper device
dmsize=`blockdev --getsize /dev/loop0`
dmsetup create

# refresh partition table
kpartx -a $LODEV
exit 0
#partprobe $LODEV

# create root filesystem
mkfs.ext4 -L root ${LODEV}p1

# mount here
mkdir rootfs
mount ${LODEV}p1 rootfs

# unpack rootfs
tar -C rootfs --numeric-owner -xpf mxchrome.tar.gz

# install bootloader
dd if=rootfs/boot/cubox-i-spl.bin of=$LODEV bs=1K seek=1
dd if=rootfs/boot/u-boot.img of=$LODEV bs=1K seek=42

# umount rootfs
umount rootfs
rmdir rootfs

# stop loop device
losetup -d $LODEV

# End
echo Done
